/* ============================================================
   data.js — seed takeoff for the demo project.

   Coordinates are in sheet units (0–1000 x, 0–750 y) matching the
   drawing viewBox, so markers sit on real plan geometry rather
   than floating on a percentage grid.
   ============================================================ */

export const STATUS = {
  ready: { key: "ready", label: "Ready to review", color: "#23528f", tint: "#e8f0fa" },
  attention: { key: "attention", label: "Needs attention", color: "#9c5f06", tint: "#fbf0dc" },
  missing: { key: "missing", label: "Missing information", color: "#b0322a", tint: "#fbe9e7" },
  approved: { key: "approved", label: "Estimator approved", color: "#1c6f47", tint: "#e6f3ec" },
  rejected: { key: "rejected", label: "Rejected", color: "#86827a", tint: "#f7f5f0" },
};

export const STATUS_ORDER = ["missing", "attention", "ready", "approved", "rejected"];

export const SYSTEMS = ["Power", "Lighting", "Distribution", "Life safety", "Low voltage", "Fire alarm"];

export const SHEETS = [
  {
    id: "E2.1",
    number: "E2.1",
    title: "Power plan — warehouse",
    discipline: "Electrical",
    revision: "Rev 2",
    revisionDate: "2026-05-14",
    scale: "mixed",
    scaleOptions: ['1/8" = 1\'-0"', '1/16" = 1\'-0"'],
    plan: "warehouse",
  },
  {
    id: "E1.1",
    number: "E1.1",
    title: "Lighting plan — first floor",
    discipline: "Electrical",
    revision: "Rev 3",
    revisionDate: "2026-06-02",
    scale: "none",
    scaleOptions: ['1/8" = 1\'-0"', '3/16" = 1\'-0"', '1/4" = 1\'-0"'],
    plan: "office",
  },
  {
    id: "E3.1",
    number: "E3.1",
    title: "Panel schedules and details",
    discipline: "Electrical",
    revision: "Rev 1",
    revisionDate: "2026-04-28",
    scale: "nts",
    scaleOptions: [],
    plan: "schedule",
  },
];

/* symbol: which glyph draws on the plan. See components/Symbols.jsx */
export const ITEMS = [
  {
    id: "it-01",
    sheetId: "E2.1",
    symbol: "panel",
    name: "Panel LP-1",
    description: "208Y/120V, 3-phase, 42-circuit, surface mounted at column B-2.",
    system: "Distribution",
    category: "Panels",
    quantity: 1,
    unit: "EA",
    status: "approved",
    approvedBy: "Dana Whitfield",
    x: 178,
    y: 214,
    notes: "",
    warning: null,
    evidence: { sheet: "E2.1", detail: "Panel tag at column B-2", crop: "panel" },
  },
  {
    id: "it-02",
    sheetId: "E2.1",
    symbol: "run",
    name: '2" EMT conduit run',
    description: "Feeder from LP-1 to warehouse floor box circuit, routed above deck.",
    system: "Power",
    category: "Conduit and wire",
    quantity: 184,
    unit: "LF",
    status: "missing",
    path: [
      [186, 226],
      [186, 430],
      [402, 430],
      [402, 508],
    ],
    notes: "",
    warning: {
      title: "Scale needs confirmation",
      found: "E2.1 shows two different scale labels — one in the title block and one under the enlarged dock plan.",
      why: "Measured conduit lengths on this sheet may be wrong until the plan scale is settled.",
      fix: "Select the scale that applies to the warehouse plan, then re-check this run.",
      where: "E2.1 title block and enlarged plan note",
    },
    evidence: { sheet: "E2.1", detail: "Title block scale note", crop: "titleblock" },
  },
  {
    id: "it-03",
    sheetId: "E2.1",
    symbol: "receptacle",
    name: "20A duplex receptacle",
    description: "Wall-mounted general purpose receptacle, +18\" AFF, warehouse perimeter.",
    system: "Power",
    category: "Devices",
    quantity: 14,
    unit: "EA",
    status: "ready",
    x: 556,
    y: 508,
    notes: "",
    warning: null,
    evidence: { sheet: "E2.1", detail: "Typical device tag, grid C-3", crop: "device" },
  },
  {
    id: "it-04",
    sheetId: "E2.1",
    symbol: "highbay",
    name: "High-bay LED fixture, type A",
    description: "Pendant mounted high bay over open warehouse, 24'-0\" mounting height.",
    system: "Lighting",
    category: "Fixtures",
    quantity: 26,
    unit: "EA",
    status: "attention",
    x: 662,
    y: 268,
    notes: "",
    warning: {
      title: "Fixture type conflicts with the schedule",
      found: "The plan tags this fixture as type A. The fixture schedule on E0.1 lists the same tag as type A1 at a different wattage.",
      why: "The two types carry different material cost and labor units, so the count would be priced against the wrong fixture.",
      fix: "Confirm which type governs, then correct the classification before approving.",
      where: "E2.1 plan tag and E0.1 luminaire schedule",
    },
    evidence: { sheet: "E0.1", detail: "Luminaire schedule, rows A and A1", crop: "schedule" },
  },
  {
    id: "it-05",
    sheetId: "E2.1",
    symbol: "disconnect",
    name: "60A disconnect switch",
    description: "Non-fused, NEMA 3R, exterior wall at loading dock, feeds dock leveler.",
    system: "Power",
    category: "Disconnects",
    quantity: 2,
    unit: "EA",
    status: "ready",
    x: 836,
    y: 592,
    notes: "",
    warning: null,
    evidence: { sheet: "E2.1", detail: "Dock equipment note", crop: "device" },
  },
  {
    id: "it-06",
    sheetId: "E2.1",
    symbol: "exit",
    name: "Exit sign, combination unit",
    description: "LED exit and emergency light, ceiling mounted with 90-minute battery.",
    system: "Life safety",
    category: "Life safety",
    quantity: 6,
    unit: "EA",
    status: "ready",
    x: 470,
    y: 138,
    notes: "",
    warning: null,
    evidence: { sheet: "E2.1", detail: "Egress path note", crop: "device" },
  },
  {
    id: "it-07",
    sheetId: "E2.1",
    symbol: "unknown",
    name: "Unclassified symbol",
    description: "A repeated symbol near the dock office was found but does not match the legend on this set.",
    system: "Power",
    category: "Unclassified",
    quantity: 3,
    unit: "EA",
    status: "attention",
    x: 748,
    y: 442,
    notes: "",
    warning: {
      title: "Symbol is not in the legend",
      found: "This symbol appears three times near the dock office and is not defined in the E0.1 legend.",
      why: "An unclassified item carries no material or labor, so it would be missing from the estimate.",
      fix: "Identify the device and set its classification, or reject it if it belongs to another trade.",
      where: "E2.1 dock office area and E0.1 symbol legend",
    },
    evidence: { sheet: "E0.1", detail: "Symbol legend, electrical", crop: "schedule" },
  },
  {
    id: "it-08",
    sheetId: "E1.1",
    symbol: "troffer",
    name: "2x4 LED troffer, type F",
    description: "Recessed lay-in troffer, open office and corridor ceiling grid.",
    system: "Lighting",
    category: "Fixtures",
    quantity: 38,
    unit: "EA",
    status: "approved",
    approvedBy: "Dana Whitfield",
    x: 402,
    y: 300,
    notes: "",
    warning: null,
    evidence: { sheet: "E1.1", detail: "Ceiling grid, open office", crop: "device" },
  },
  {
    id: "it-09",
    sheetId: "E1.1",
    symbol: "run",
    name: '1" EMT conduit run',
    description: "Branch circuit home run from lighting panel to corridor fixtures.",
    system: "Lighting",
    category: "Conduit and wire",
    quantity: 96,
    unit: "LF",
    status: "missing",
    path: [
      [232, 232],
      [232, 372],
      [468, 372],
    ],
    notes: "",
    warning: {
      title: "Missing scale reference",
      found: "No scale label was found in the E1.1 title block.",
      why: "Without a scale, this run could not be measured and its length is an estimate only.",
      fix: "Set the drawing scale for E1.1, or calibrate against a known dimension on the plan.",
      where: "E1.1 title block",
    },
    evidence: { sheet: "E1.1", detail: "Title block", crop: "titleblock" },
  },
  {
    id: "it-10",
    sheetId: "E1.1",
    symbol: "switch",
    name: "Single-pole wall switch",
    description: "Toggle switch at office and conference room doors, +48\" AFF.",
    system: "Lighting",
    category: "Devices",
    quantity: 11,
    unit: "EA",
    status: "ready",
    x: 596,
    y: 254,
    notes: "",
    warning: null,
    evidence: { sheet: "E1.1", detail: "Typical switch tag", crop: "device" },
  },
  {
    id: "it-11",
    sheetId: "E1.1",
    symbol: "junction",
    name: '4" square junction box',
    description: "Concealed above ceiling, lighting circuit splice point.",
    system: "Lighting",
    category: "Boxes",
    quantity: 9,
    unit: "EA",
    status: "ready",
    x: 300,
    y: 466,
    notes: "",
    warning: null,
    evidence: { sheet: "E1.1", detail: "Ceiling plan detail 3", crop: "device" },
  },
  {
    id: "it-12",
    sheetId: "E1.1",
    symbol: "data",
    name: "Data outlet, 2-port",
    description: "Cat 6 outlet at workstations, ring and string by electrical contractor.",
    system: "Low voltage",
    category: "Devices",
    quantity: 22,
    unit: "EA",
    status: "ready",
    x: 700,
    y: 430,
    notes: "",
    warning: null,
    evidence: { sheet: "E1.1", detail: "Workstation typical", crop: "device" },
  },
];
