"""actions

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-07 18:45:58.211521

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('sheet_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('undoes_action_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['undoes_action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_actions_project_id'), 'actions', ['project_id'], unique=False)
    op.create_index(op.f('ix_actions_undoes_action_id'), 'actions', ['undoes_action_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        create or replace function actions_are_append_only() returns trigger as $$
        begin
            raise exception 'actions is append-only: % is not permitted', tg_op;
        end;
        $$ language plpgsql;

        create trigger actions_no_update before update on actions
            for each statement execute function actions_are_append_only();

        create trigger actions_no_delete before delete on actions
            for each statement execute function actions_are_append_only();
        """
    )


def downgrade() -> None:
    op.execute(
        """
        drop trigger if exists actions_no_update on actions;
        drop trigger if exists actions_no_delete on actions;
        drop function if exists actions_are_append_only();
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_undoes_action_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_project_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
