"""actions

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-07 18:45:58.211521

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.takeoff.actions import ACTION_LOG_GUARD_DDL, ACTION_LOG_GUARD_TEARDOWN_DDL

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('sheet_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('undoes_action_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    # RESTRICT, not CASCADE: this log must outlive its subject. A project
    # delete that would erase its own action history in the same
    # statement is exactly the failure this table exists to prevent --
    # the same reasoning that already kept item_id/sheet_id off any
    # foreign key at all (see below).
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['undoes_action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # item_id and sheet_id (above) are deliberately plain UUID columns
    # with no foreign key at all -- a deleted item or sheet must not take
    # its history with it, and RESTRICT isn't available there since a
    # sheet/item delete is a normal, expected operation this log must
    # survive rather than block.
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_actions_project_id'), 'actions', ['project_id'], unique=False)
    op.create_index(op.f('ix_actions_seq'), 'actions', ['seq'], unique=True)
    # Partial unique: at most one action may claim to undo a given
    # action; most actions undo nothing, so NULL stays unconstrained.
    op.create_index(
        'uq_actions_undoes_action_id', 'actions', ['undoes_action_id'],
        unique=True, postgresql_where=sa.text('undoes_action_id is not null'),
    )
    # ### end Alembic commands ###

    op.execute(ACTION_LOG_GUARD_DDL)


def downgrade() -> None:
    op.execute(ACTION_LOG_GUARD_TEARDOWN_DDL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_actions_undoes_action_id', table_name='actions')
    op.drop_index(op.f('ix_actions_seq'), table_name='actions')
    op.drop_index(op.f('ix_actions_project_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
