"""warning_reason

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-09 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# A plain sa.Enum, not app.takeoff.models.WarningReason, so this migration
# reads correctly against whatever the model looked like the day it was
# written -- the same reason 0003 spells out review_status's members by
# hand ('ready', 'attention', ...) instead of importing ReviewStatus.
warning_reason = sa.Enum('scale', 'legend', name='warning_reason')


def upgrade() -> None:
    # op.add_column(), unlike op.create_table(), does not create the enum
    # type as a side effect -- it has to exist first, or the ADD COLUMN
    # fails trying to reference a type that isn't there yet.
    warning_reason.create(op.get_bind(), checkfirst=False)
    op.add_column('warnings', sa.Column('reason', warning_reason, nullable=True))

    # There is no production data yet, but the pattern is what matters: a
    # NOT NULL column added to a table that may already have rows must
    # backfill before the constraint lands, not skip the step because
    # today's environment happens to have nothing to fix. Every Warning
    # row this schema has ever produced came from set_scale()
    # (app/takeoff/scale.py), and that function only ever explains a
    # missing scale -- 'scale' is the correct backfill value for
    # anything written before this column existed, not an arbitrary
    # placeholder.
    op.execute("update warnings set reason = 'scale' where reason is null")

    op.alter_column('warnings', 'reason', nullable=False)


def downgrade() -> None:
    op.drop_column('warnings', 'reason')

    # A Postgres native enum is an object independent of the column that
    # used it -- dropping the column does not drop the type. Drop it
    # explicitly, after the only column that referenced it is gone, or
    # the type is orphaned and the next upgrade fails trying to create a
    # type that already exists.
    warning_reason.drop(op.get_bind(), checkfirst=False)
