"""presence

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-12 16:30:52.435380

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presence',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sheet_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index('ix_presence_project_id_seen_at', 'presence', ['project_id', 'seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_presence_project_id_seen_at', table_name='presence')
    op.drop_table('presence')
    # ### end Alembic commands ###
