"""warning_reason_schedule_conflict

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-13 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.

Adds a third `WarningReason`: 'schedule_conflict'. This is a deliberate,
visible expansion of the closed vocabulary CLAUDE.md describes -- not a
routine migration. The seed fixture (app/seed.py, porting
src/lib/data.js) carries a warning, "Fixture type conflicts with the
schedule," that is neither a scale problem nor a legend problem: the plan
tags a fixture as one type and the E0.1 luminaire schedule lists the same
tag as another.

Tagging it SCALE just to make it fit the existing two values was rejected
outright. `set_scale()` (app/takeoff/scale.py) deletes every warning
whose `reason` is SCALE when a sheet's scale is confirmed, on the theory
that a scale warning is about the scale and nothing else. A schedule
conflict tagged SCALE would be silently destroyed the moment an estimator
merely confirmed the drawing's scale -- discarding evidence about a
fixture disagreement that estimator never saw and never resolved, exactly
the failure `Warning.reason` was introduced to make impossible
(0005_warning_reason.py). Named for what it actually is,
SCHEDULE_CONFLICT, rather than a catch-all OTHER -- a junk-drawer value
would stop the vocabulary from being closed at all.

Practical consequence for later work: the takeoff engine (Track 2) will
eventually emit warnings of its own and has to classify every one of them
into this now-three-member enum. There is no default reason a real
warning can fall back to.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres allows adding a value to an existing enum type in place --
    # unlike 0005, which had to CREATE the type from scratch because the
    # column using it was itself new, this migration only widens an
    # already-live vocabulary. ADD VALUE runs fine inside Alembic's
    # per-migration transaction on Postgres 12+, as long as the new value
    # is not *used* within that same transaction -- this migration only
    # adds it and never writes a row with it, so that restriction never
    # bites here.
    op.execute("ALTER TYPE warning_reason ADD VALUE 'schedule_conflict'")


def downgrade() -> None:
    # Postgres has no "ALTER TYPE ... DROP VALUE" (still true as of 16 --
    # see the Postgres manual's ALTER TYPE page). The only way back is to
    # rebuild the type from scratch with the narrower value list and
    # repoint the column at it -- the same rename/create/swap/drop shape
    # 0005's downgrade used for a type it could drop outright, because
    # the column referencing it was also being dropped there. Here the
    # `warnings.reason` column stays, so the swap has to happen with its
    # data intact.
    #
    # A row that actually uses 'schedule_conflict' cannot be represented
    # in the narrower type at all -- there is no other reason to fall
    # back to that doesn't misrepresent what the row means. Refuse the
    # downgrade loudly rather than let Postgres's own "invalid input
    # value for enum warning_reason" error be the first anyone hears of
    # it, or worse, let some future version of this migration silently
    # coerce the row to a wrong reason.
    conn = op.get_bind()
    in_use = conn.execute(
        sa.text("select count(*) from warnings where reason = 'schedule_conflict'")
    ).scalar()
    if in_use:
        raise RuntimeError(
            f"{in_use} warning row(s) use reason='schedule_conflict'. Postgres cannot "
            "drop a single enum value, and rebuilding the type would misrepresent those "
            "rows under one of the remaining reasons. Reclassify or delete them before "
            "downgrading past 0007."
        )

    op.execute("ALTER TYPE warning_reason RENAME TO warning_reason_old")
    narrower = sa.Enum('scale', 'legend', name='warning_reason')
    narrower.create(conn, checkfirst=False)
    op.execute(
        "ALTER TABLE warnings ALTER COLUMN reason TYPE warning_reason "
        "USING reason::text::warning_reason"
    )
    op.execute("DROP TYPE warning_reason_old")
