"""item_version

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-15 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.

Adds `items.version`, the optimistic-concurrency counter task-13b-brief.md
introduces for the five single-item mutations (approve, reject, unreject,
edit, delete). Not `updated_at` (already on this table, but transaction-
constant per Task 5's finding) and not SQLAlchemy's `version_id_col` (it
cannot see client staleness once every write already re-reads under
`FOR UPDATE` -- see `app/takeoff/concurrency.py`'s module docstring).

Same shape as 0005/0007: nullable column first, backfill, then NOT NULL --
a NOT NULL column landing on a table that may already have rows must
backfill before the constraint applies, not skip the step because today's
environment happens to have nothing to fix. Every row this schema has
ever produced predates the concurrency check entirely, so 1 -- the same
value `Item.version`'s Python-side default now assigns to every new row
-- is the correct backfill value, not an arbitrary placeholder.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('items', sa.Column('version', sa.Integer(), nullable=True))
    op.execute("update items set version = 1 where version is null")
    op.alter_column('items', 'version', nullable=False)


def downgrade() -> None:
    op.drop_column('items', 'version')
