"""project_fields

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-18 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.

Adds the columns spec §5.1's projects dashboard table renders (task-1-brief.md).
Text columns get a server_default of '' -- and the two facts that are
genuinely optional at creation (bid date, assigned estimator) stay
nullable -- so the migration is safe against existing rows without a data
backfill step, matching 0005/0007/0008's nullable-then-backfill shape
minus the backfill, since '' and NULL are both valid defaults here rather
than placeholders standing in for a value every row needs.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('projects', sa.Column('number', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('customer', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('location', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('bid_due_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('estimator_user_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'fk_projects_estimator_user_id', 'projects', 'users',
        ['estimator_user_id'], ['id'], ondelete='SET NULL',
    )
    op.create_index(op.f('ix_projects_estimator_user_id'), 'projects', ['estimator_user_id'], unique=False)
    op.add_column('projects', sa.Column('stage', sa.String(length=50), nullable=False, server_default='setup'))
    op.add_column('projects', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'projects',
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )


def downgrade() -> None:
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'archived_at')
    op.drop_column('projects', 'stage')
    op.drop_index(op.f('ix_projects_estimator_user_id'), table_name='projects')
    op.drop_constraint('fk_projects_estimator_user_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'estimator_user_id')
    op.drop_column('projects', 'bid_due_date')
    op.drop_column('projects', 'location')
    op.drop_column('projects', 'customer')
    op.drop_column('projects', 'number')
