"""project_created_by

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-20 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
(0001, 0002, ...) rather than the autogenerated hash, so the chain and the
directory listing always agree. Set the id by hand after each
`alembic revision --autogenerate` and rename the file to match.

Records who created a project. ROADMAP.md invariant 8 says every mutation
is attributable, and project creation was the one mutation with no `by`
anywhere -- the action log is project-scoped, so a creation has no project
to belong to yet, which is why this is a column rather than a log row.

Nullable with no backfill, deliberately: rows that predate this column
were created by someone we cannot now identify, and inventing an owner for
them would be worse than an honest NULL. That is also the reason this
lands now rather than later -- `created_by_user_id` cannot be backfilled,
so every project created before the column exists is permanently
anonymous.

ON DELETE SET NULL rather than RESTRICT: deprovisioning an estimator must
not be blocked by projects they started, and the action log retains the
real history of what they did.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('projects', sa.Column('created_by_user_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'fk_projects_created_by_user_id', 'projects', 'users',
        ['created_by_user_id'], ['id'], ondelete='SET NULL',
    )
    op.create_index(
        op.f('ix_projects_created_by_user_id'), 'projects', ['created_by_user_id'], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_projects_created_by_user_id'), table_name='projects')
    op.drop_constraint('fk_projects_created_by_user_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by_user_id')
