"""engine_ingest_columns

Revision ID: 0011
Revises: 0010
Create Date: 2026-08-27 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
rather than the autogenerated hash, so the chain and the directory
listing always agree.

Adds the columns the takeoff engine produces and the built UI already
renders: per-sheet page metadata (so the canvas can fetch the right page
image and normalize marker coordinates against the right page size) and
per-item cost, placements, and the vision-pass confirmation flag.

Every column is defaulted or nullable, so no backfill step is needed --
the only rows that exist are fixtures being deleted in the same slice.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('sheets', sa.Column('takeoff_id', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('sheets', sa.Column('page_index', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sheets', sa.Column('width_pt', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sheets', sa.Column('height_pt', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sheets', sa.Column('unreadable_reason', sa.Text(), nullable=False, server_default=''))
    op.add_column('sheets', sa.Column('ai_reading', JSONB(), nullable=True))

    op.add_column('items', sa.Column('material_cost', sa.Numeric(12, 2), nullable=False, server_default='0'))
    op.add_column('items', sa.Column('labor_hours', sa.Numeric(12, 2), nullable=False, server_default='0'))
    op.add_column('items', sa.Column('labor_cost', sa.Numeric(12, 2), nullable=False, server_default='0'))
    op.add_column('items', sa.Column('total_cost', sa.Numeric(12, 2), nullable=False, server_default='0'))
    op.add_column('items', sa.Column('placements', JSONB(), nullable=True))
    op.add_column('items', sa.Column('ai_confirmed', sa.Boolean(), nullable=False, server_default='false'))


def downgrade() -> None:
    for col in ('ai_confirmed', 'placements', 'total_cost', 'labor_cost', 'labor_hours', 'material_cost'):
        op.drop_column('items', col)
    for col in ('ai_reading', 'unreadable_reason', 'height_pt', 'width_pt', 'page_index', 'takeoff_id'):
        op.drop_column('sheets', col)
