"""notes

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-28 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
rather than the autogenerated hash, so the chain and the directory
listing always agree.

Adds the notes table, and items.source_tag -- the engine cluster tag,
which is the key an approval-preserving re-run matches on. Both are
additive: source_tag defaults to '' so existing rows are valid.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision: str = '0012'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('items', sa.Column('source_tag', sa.String(length=50), nullable=False, server_default=''))
    op.create_table(
        'notes',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('project_id', UUID(as_uuid=True), sa.ForeignKey('projects.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('scope', sa.String(length=20), nullable=False, server_default='project'),
        sa.Column('scope_ref', UUID(as_uuid=True), nullable=True),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=40), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='open'),
        sa.Column('rfi_needed', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('usage', sa.String(length=20), nullable=False, server_default='reference'),
        sa.Column('source_ref', sa.String(length=300), nullable=False, server_default=''),
        sa.Column('obsolete_after_revision', sa.String(length=100), nullable=False, server_default=''),
        sa.Column('author_user_id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='RESTRICT'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_table('notes')
    op.drop_column('items', 'source_tag')
