"""item_evidence_images

Revision ID: 0013
Revises: 0012
Create Date: 2026-08-30 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
rather than the autogenerated hash, so the chain and the directory
listing always agree.

A crop of the source drawing per item, kept in its own table rather than
a new items column so the undo/snapshot machinery (which walks every
mapped Item column automatically) never has to reason about binary data.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision: str = '0013'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'item_evidence_images',
        sa.Column('item_id', UUID(as_uuid=True), sa.ForeignKey('items.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('png', sa.LargeBinary(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table('item_evidence_images')
