"""pricing_source

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-31 00:00:00.000000

Convention: revision ids match the versions/ filename sequence number
rather than the autogenerated hash, so the chain and the directory
listing always agree.

Two columns on projects recording which mechanism (llm or deterministic)
actually priced the most recent ingest/reprocess, and its one-sentence
basis -- Labor and Material Pricing's precedence resolution reads these
to decide whether the engine's own cost figures are trustworthy enough
to show as a baseline tier.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('projects', sa.Column('pricing_source', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('pricing_note', sa.Text(), nullable=False, server_default=''))


def downgrade() -> None:
    op.drop_column('projects', 'pricing_note')
    op.drop_column('projects', 'pricing_source')
